FROM node:8 as react-stage
WORKDIR /app

COPY package*.json ./
RUN yarn
COPY . .

RUN yarn build

# Stage 2: nginx
FROM nginx

COPY --from=react-stage /app/build/ /usr/share/nginx/html/
COPY --from=react-stage /app/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
